"""add tasks model

Revision ID: 67784282f034
Revises: 70ea0d2e0784
Create Date: 2018-09-26 17:27:26.519830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67784282f034'
down_revision = '70ea0d2e0784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_date'), 'task', ['created_date'], unique=False)
    op.create_index(op.f('ix_task_updated_date'), 'task', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_updated_date'), table_name='task')
    op.drop_index(op.f('ix_task_created_date'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
